# Generated by Django 4.2.13 on 2024-06-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_alter_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover_art/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.station'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
