# Generated by Django 4.2.13 on 2024-07-01 17:45

import chikcam.music_player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_track_album_track_artist_track_cover_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to=chikcam.music_player.models.cover_art_upload_to),
        ),
    ]
