# Generated by Django 4.2.13 on 2024-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('feed_snack', 'Feed Snack'), ('flashlight', 'Flashlight'), ('text_to_talk', 'Text to Talk'), ('play_song', 'Play Song'), ('take_pic', 'Take a Pic')], max_length=50)),
                ('activation_count', models.IntegerField(default=0)),
                ('last_activated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
