# Generated by Django 4.2.13 on 2024-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_chicken',
            field=models.CharField(blank=True, max_length=255, verbose_name='Favorite Chicken'),
        ),
    ]
