# Generated by Django 4.2.13 on 2024-05-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_chicken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=1, verbose_name='Credits'),
        ),
    ]
