name: re-deploy on main push or merge
on:
  push:
    branches: ['master', 'main']
    
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: cd /root/gsa_manager && docker-compose -f docker-compose.production.yml down && git pull && docker-compose -f docker-compose.production.yml build && docker-compose -f docker-compose.production.yml run --rm django python manage.py migrate && docker-compose -f docker-compose.production.yml up -d
